# Generated by Django 2.2.2 on 2019-07-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0005_auto_20190706_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='palavras_chave',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
