# Generated by Django 2.2.2 on 2019-07-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0007_auto_20190706_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='link_audio',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='link_externo',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='link_foto',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='link_georreferenciamento',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='link_video',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumo',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=models.TextField(max_length=600),
        ),
    ]
