# Generated by Django 2.2.2 on 2019-07-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0009_noticia_dia_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='dia_publicacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
