# Generated by Django 2.2.6 on 2019-12-02 03:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_est', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title2',
            field=models.CharField(default=datetime.datetime(2019, 12, 2, 3, 30, 49, 683692, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
