# Generated by Django 2.2.6 on 2019-12-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_est', '0002_book_title2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
