# Generated by Django 2.2.6 on 2019-12-02 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_est', '0004_auto_20191202_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title2',
            new_name='link',
        ),
    ]
