# Generated by Django 2.2.6 on 2019-12-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_est', '0005_auto_20191202_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, upload_to='books/pdfs'),
        ),
    ]
