# Generated by Django 2.2.7 on 2019-11-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='FormNews',
        ),
    ]
