# Generated by Django 2.2.7 on 2019-11-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191125_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='formnews',
            name='predicao',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
