# Generated by Django 2.2.7 on 2019-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_formnews_predicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formnews',
            name='predicao',
            field=models.FloatField(blank=True),
        ),
    ]
