# Generated by Django 2.2.7 on 2019-11-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191125_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formnews',
            old_name='veiculo',
            new_name='url',
        ),
    ]
