# Generated by Django 2.2.7 on 2019-11-13 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_avatar', models.ImageField(blank=True, null=True, upload_to='assets/images')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('nome_completo', models.CharField(max_length=100)),
                ('semestre', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['primeiro_nome', 'sobrenome'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField(max_length=1000)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='assets/images')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitecampus.Autor')),
            ],
        ),
    ]
