# Generated by Django 2.2.7 on 2019-11-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecampus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='semestre',
            field=models.CharField(choices=[('1', '2019/1'), ('2', '2018/2'), ('3', '2018/1'), ('4', '2017/2')], max_length=1),
        ),
    ]
