# Generated by Django 2.2.7 on 2019-11-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecampus', '0002_auto_20191113_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
