# Generated by Django 2.2.7 on 2019-11-21 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitecampus', '0003_auto_20191118_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='editoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitecampus.Editoria'),
        ),
    ]
