# Generated by Django 2.2.7 on 2019-11-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecampus', '0006_post_sutia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='semestre',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='semestrepub',
            field=models.CharField(max_length=6),
        ),
    ]
