# Generated by Django 2.2.7 on 2019-11-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecampus', '0007_auto_20191121_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='semestrepub',
            field=models.CharField(help_text='x/20xx', max_length=6),
        ),
    ]
