# Generated by Django 2.2.7 on 2019-11-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecampus', '0008_auto_20191121_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='semestrepub',
            new_name='semestre_publicação',
        ),
    ]
