# Generated by Django 2.2.7 on 2019-11-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecampus', '0009_auto_20191121_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='semestre',
            field=models.CharField(help_text='20xx/x', max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('1', 'Rascunho'), ('2', 'Em Revisão'), ('3', 'Pronto')], default='Rascunho', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='semestre_publicação',
            field=models.CharField(help_text='20xx/x', max_length=6),
        ),
    ]
