# Generated by Django 2.2.7 on 2019-11-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecampus', '0010_auto_20191121_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hierarquia',
            field=models.CharField(choices=[('1', 'Primaria'), ('2', 'Secundaria'), ('3', 'Terciaria')], default='', max_length=1),
        ),
    ]
