# Generated by Django 2.2.7 on 2019-11-22 13:16

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('sitecampus', '0011_post_hierarquia'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('1', 'Rascunho'), ('2', 'Em Revisão'), ('3', 'Pronto')], default='1', max_length=1),
        ),
    ]
