# Generated by Django 2.2.7 on 2019-11-26 17:22

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecampus', '0012_auto_20191122_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='sutia',
            field=djrichtextfield.models.RichTextField(blank=True, max_length=200, null=True),
        ),
    ]
