# Generated by Django 2.2.7 on 2019-12-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecampus', '0014_auto_20191126_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.CharField(blank=True, help_text='url da imagem hospedada', max_length=90, null=True),
        ),
    ]
