# Generated by Django 2.2.2 on 2019-07-06 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0002_auto_20190705_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cod_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_noticia', to=settings.AUTH_USER_MODEL),
        ),
    ]
