# Generated by Django 2.2.2 on 2019-07-06 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0003_auto_20190705_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
