# Generated by Django 2.2.2 on 2019-07-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0006_auto_20190706_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='palavras_chave',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
