# Generated by Django 2.2.2 on 2019-07-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0008_auto_20190707_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='dia_publicacao',
            field=models.DateField(default='2019-01-01'),
        ),
    ]
