# Generated by Django 2.2.4 on 2019-11-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0010_auto_20190707_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='palavras_chave',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
