# Generated by Django 2.2.4 on 2019-12-07 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0012_auto_20191207_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='usuarios',
            field=models.ManyToManyField(related_name='usuario_noticia', to=settings.AUTH_USER_MODEL),
        ),
    ]
