# Generated by Django 3.2.3 on 2021-06-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0013_auto_20191207_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('numero_telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
