# Generated by Django 3.2.3 on 2021-10-21 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0015_noticia_autoria_midia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='resumo',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_video_long_form', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('autoria_midia_video', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_app.noticia')),
            ],
        ),
        migrations.CreateModel(
            name='TextoMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(max_length=200)),
                ('texto_materia', models.TextField(max_length=2000)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_app.noticia')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_foto_long_form', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('autoria_midia_imagem', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_app.noticia')),
            ],
        ),
    ]
