# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 02:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion

from newsroomFramework.settings import PROJECT_ROOT
import os
import ontospy

def forwards_func(apps, schema_editor):

    Namespace = apps.get_model("cms", "Namespace")
    Recurso = apps.get_model("cms", "Recurso")
    db_alias = schema_editor.connection.alias
    
    ontoZika = ontospy.Ontospy(os.path.join(PROJECT_ROOT, 'root-ontology.owl'))
    ontoAO = ontospy.Ontospy(os.path.join(PROJECT_ROOT, 'annotation-core.owl'))

    nsZika = Namespace(ns_ref=str(ontoZika.namespaces[0][1]).partition(')')[0],rdf=open(os.path.join(PROJECT_ROOT, 'root-ontology.owl'),'r').read())
    nsAO = Namespace(ns_ref=str(ontoAO.namespaces[0][1]).partition(')')[0],rdf=open(os.path.join(PROJECT_ROOT, 'annotation-core.owl'),'r').read())
    
    nsZika.save()
    nsAO.save()

    for i in ontoZika.classes:
        Recurso.objects.using(db_alias).bulk_create([
           Recurso(namespace=nsZika,uri=i,valor=str(i).partition('#')[-1].partition('*')[0].replace('_',' ')),
        ])

    for i in ontoAO.properties:
        Recurso.objects.using(db_alias).bulk_create([
            Recurso(namespace=nsAO,uri=i,valor=str(i).split('/')[-1].partition('*')[0]),
        ])
     
def reverse_func(apps, schema_editor):

    Namespace = apps.get_model("cms", "Namespace")
    Recurso = apps.get_model("cms", "Recurso")
    db_alias = schema_editor.connection.alias

    Recurso.objects.using(db_alias).all().delete()
    Namespace.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sutian', models.CharField(max_length=50)),
                ('text', ckeditor.fields.RichTextField(default='', verbose_name='Matéria')),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Editoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns_ref', models.TextField(verbose_name='ref')),
                ('rdf', models.TextField(verbose_name='rdf')),
            ],
        ),
        migrations.CreateModel(
            name='Publicado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(verbose_name='html')),
                ('rdf_annotation', models.TextField(verbose_name='rdf_annotation')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Artigo')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', ckeditor.fields.RichTextField(verbose_name='uri')),
                ('valor', ckeditor.fields.RichTextField(verbose_name='valor')),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Namespace')),
            ],
        ),
        migrations.CreateModel(
            name='Tripla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Artigo')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objeto', to='cms.Recurso')),
                ('predicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicado', to='cms.Recurso')),
            ],
        ),
        migrations.AddField(
            model_name='artigo',
            name='creators',
            field=models.ManyToManyField(to='cms.Creator'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='editoria',
            field=models.ManyToManyField(to='cms.Editoria'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
