# Generated by Django 2.0.3 on 2018-03-28 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_publicado_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='namespace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Namespace'),
        ),
    ]
