# Generated by Django 2.0.3 on 2018-04-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20180328_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='sutian',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
