# Generated by Django 2.0.3 on 2018-04-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20180417_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='sutian',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
